---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: consumer
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: consumer
rules:
  - apiGroups:
      - "batch"
    resources:
      - jobs
    verbs:
      - create
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: consumer
  namespace: default
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: consumer
