name: CI test

on:
  push:
    branches:
      - master

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.2"
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.57.2
      - name: Install mockery
        run: go install github.com/vektra/mockery/v2@v2.43.1
      - name: Generate mocks
        run: make generate
      - name: Lint
        run: make check

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.2"
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install mockery
        run: go install github.com/vektra/mockery/v2@v2.43.1
      - name: Generate mocks
        run: make generate
      - name: Test
        run: make test